
version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: flight-mngr
      POSTGRES_PASSWORD: xd
      POSTGRES_DB: flight-mngr
    ports:
      - 5432:5432
