services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - 5432:5432
    
  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
