name: Test

on:
  push:
    branches:
    - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --all-targets --verbose

    - name: Run tests
      run: cargo test --verbose
