name: Test

on:
  push:
    branches:
    - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
    - name: Setup cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build
      run: cargo build --all-targets --verbose

    - name: Run tests
      run: cargo test --verbose
